@@ .. @@
 import { ArrowLeft, Plus, Camera, Calendar, DollarSign, Building2, Wrench, Paintbrush, Leaf, Shield, Zap, Droplets, ChevronRight } from 'lucide-react-native';
+import { Bug, Waves, TreePine, Home, Trash2 } from 'lucide-react-native';
 import { CommercialColors, CommercialTypography, CommercialBorderRadius, CommercialSpacing } from '@/themes/commercialDesignSystem';
 import type { CommercialProperty } from '@/types/commercial';
 
@@ -32,9 +33,9 @@ const MOCK_PROPERTIES: CommercialProperty[] = [
   {
     id: 'prop-1',
     name: 'Downtown Office Tower',
-    address: '123 Business Ave',
-    city: 'Los Angeles',
-    state: 'CA',
-    zipCode: '90210',
+    address: '123 Congress Ave',
+    city: 'Austin',
+    state: 'TX',
+    zipCode: '78701',
     propertyType: 'office',
     squareFootage: 150000,
     floors: 25,
@@ .. @@
   {
     id: 'prop-2',
     name: 'Westside Retail Center',
-    address: '456 Commerce St',
-    city: 'Santa Monica',
-    state: 'CA',
-    zipCode: '90401',
+    address: '456 South Lamar Blvd',
+    city: 'Austin',
+    state: 'TX',
+    zipCode: '78704',
     propertyType: 'retail',
     squareFootage: 75000,
     floors: 2,
@@ .. @@
   {
     id: 'prop-3',
     name: 'Industrial Park Unit A',
-    address: '789 Industrial Blvd',
-    city: 'Carson',
-    state: 'CA',
-    zipCode: '90745',
+    address: '789 East Riverside Dr',
+    city: 'Austin',
+    state: 'TX',
+    zipCode: '78741',
     propertyType: 'warehouse',
     squareFootage: 200000,
     floors: 1,
@@ .. @@
 const PROPERTY_TYPE_SERVICES = {
   'office': [
     {
-      id: 'hvac-upgrade',
-      name: 'HVAC System Upgrade',
-      description: 'Upgrade your HVAC system for better energy efficiency and performance',
-      icon: Zap,
-      estimatedCost: '15,000 - 50,000',
-      estimatedTime: '2-4 weeks',
+      id: 'pest-upgrade',
+      name: 'Enhanced Pest Control',
+      description: 'Comprehensive pest prevention and monitoring system for office buildings',
+      icon: Bug,
+      estimatedCost: '2,000 - 5,000',
+      estimatedTime: '1-2 weeks',
     },
     {
-      id: 'smart-lighting',
-      name: 'Smart Lighting Installation',
-      description: 'Install smart lighting systems with motion sensors and energy monitoring',
-      icon: Zap,
-      estimatedCost: '8,000 - 25,000',
+      id: 'exterior-upgrade',
+      name: 'Building Exterior Enhancement',
+      description: 'Professional pressure washing, window cleaning, and facade maintenance',
+      icon: Home,
+      estimatedCost: '5,000 - 15,000',
       estimatedTime: '1-2 weeks',
     },
     {
       id: 'office-renovation',
       name: 'Office Space Renovation',
       description: 'Modernize your office space with new layouts, furniture, and finishes',
       icon: Paintbrush,
       estimatedCost: '50,000 - 200,000',
       estimatedTime: '4-12 weeks',
     },
-    {
-      id: 'security-upgrade',
-      name: 'Security System Upgrade',
-      description: 'Enhance building security with modern access control and surveillance',
-      icon: Shield,
-      estimatedCost: '10,000 - 30,000',
-      estimatedTime: '2-3 weeks',
-    },
   ],
   'retail': [
     {
       id: 'storefront-renovation',
       name: 'Storefront Renovation',
       description: 'Update your storefront with modern design and improved visibility',
       icon: Paintbrush,
       estimatedCost: '20,000 - 75,000',
       estimatedTime: '3-6 weeks',
     },
     {
-      id: 'retail-lighting',
-      name: 'Retail Lighting Upgrade',
-      description: 'Enhance product displays with specialized retail lighting solutions',
-      icon: Zap,
-      estimatedCost: '5,000 - 15,000',
+      id: 'landscape-upgrade',
+      name: 'Landscape Enhancement',
+      description: 'Enhance curb appeal with professional landscaping and garden design',
+      icon: Leaf,
+      estimatedCost: '8,000 - 25,000',
       estimatedTime: '1-2 weeks',
     },
     {
-      id: 'security-system',
-      name: 'Retail Security System',
-      description: 'Install comprehensive security with inventory protection features',
-      icon: Shield,
-      estimatedCost: '8,000 - 25,000',
-      estimatedTime: '1-3 weeks',
-    },
-    {
-      id: 'hvac-retail',
-      name: 'HVAC Optimization',
-      description: 'Optimize HVAC for retail environments with customer comfort focus',
-      icon: Zap,
-      estimatedCost: '10,000 - 30,000',
-      estimatedTime: '2-4 weeks',
+      id: 'waste-optimization',
+      name: 'Waste Management Optimization',
+      description: 'Implement efficient waste and recycling systems for retail operations',
+      icon: Trash2,
+      estimatedCost: '3,000 - 8,000',
+      estimatedTime: '1-2 weeks',
     },
   ],
   'warehouse': [
     {
       id: 'loading-dock',
       name: 'Loading Dock Upgrade',
       description: 'Modernize loading docks with improved safety and efficiency features',
       icon: Wrench,
       estimatedCost: '25,000 - 100,000',
       estimatedTime: '3-8 weeks',
     },
     {
-      id: 'warehouse-lighting',
-      name: 'Industrial Lighting System',
-      description: 'High-efficiency lighting designed for warehouse environments',
-      icon: Zap,
-      estimatedCost: '15,000 - 50,000',
-      estimatedTime: '2-4 weeks',
-    },
-    {
-      id: 'floor-resurfacing',
-      name: 'Concrete Floor Resurfacing',
-      description: 'Repair and resurface concrete floors for durability and safety',
+      id: 'exterior-industrial',
+      name: 'Industrial Exterior Maintenance',
+      description: 'Specialized exterior cleaning and maintenance for warehouse facilities',
+      icon: Home,
+      estimatedCost: '10,000 - 30,000',
+      estimatedTime: '2-4 weeks',
+    },
+    {
+      id: 'pest-industrial',
+      name: 'Industrial Pest Control',
+      description: 'Comprehensive pest management for warehouse and storage facilities',
+      icon: Bug,
+      estimatedCost: '3,000 - 8,000',
+      estimatedTime: '1-2 weeks',
+    },
+  ],
+  'mixed_use': [
+    {
+      id: 'mixed-renovation',
+      name: 'Mixed-Use Renovation',
+      description: 'Comprehensive renovation for mixed-use properties',
       icon: Paintbrush,
-      estimatedCost: '30,000 - 120,000',
-      estimatedTime: '2-6 weeks',
+      estimatedCost: '100,000 - 500,000',
+      estimatedTime: '8-24 weeks',
     },
     {
-      id: 'warehouse-security',
-      name: 'Warehouse Security System',
-      description: 'Comprehensive security with inventory and access control',
-      icon: Shield,
-      estimatedCost: '20,000 - 60,000',
-      estimatedTime: '2-5 weeks',
+      id: 'mixed-landscape',
+      name: 'Mixed-Use Landscaping',
+      description: 'Specialized landscaping solutions for diverse tenant requirements',
+      icon: Leaf,
+      estimatedCost: '15,000 - 40,000',
+      estimatedTime: '3-6 weeks',
     },
   ],
-  'mixed_use': [
+  'industrial': [
     {
-      id: 'mixed-renovation',
-      name: 'Mixed-Use Renovation',
-      description: 'Comprehensive renovation for mixed-use properties',
+      id: 'industrial-exterior',
+      name: 'Industrial Exterior Services',
+      description: 'Heavy-duty exterior cleaning and maintenance for industrial facilities',
+      icon: Home,
+      estimatedCost: '20,000 - 60,000',
+      estimatedTime: '2-6 weeks',
+    },
+    {
+      id: 'industrial-waste',
+      name: 'Industrial Waste Management',
+      description: 'Specialized waste handling and disposal for industrial operations',
+      icon: Trash2,
+      estimatedCost: '10,000 - 30,000',
+      estimatedTime: '2-4 weeks',
+    },
+  ],
+  'other': [
+    {
+      id: 'general-renovation',
+      name: 'General Renovation',
+      description: 'Comprehensive property renovation and modernization',
       icon: Paintbrush,
-      estimatedCost: '100,000 - 500,000',
-      estimatedTime: '8-24 weeks',
+      estimatedCost: 'Varies',
+      estimatedTime: 'Varies',
     },
     {
-      id: 'mixed-hvac',
-      name: 'Multi-Zone HVAC System',
-      description: 'Specialized HVAC solutions for mixed residential and commercial spaces',
-      icon: Zap,
-      estimatedCost: '40,000 - 150,000',
-      estimatedTime: '4-10 weeks',
+      id: 'custom-project',
+      name: 'Custom Project',
+      description: 'Tailored solutions for your specific property needs',
+      icon: Wrench,
+      estimatedCost: 'Custom quote',
+      estimatedTime: 'Based on requirements',
     },
+  ],
+};
+
+// Common services available for all property types
+const COMMON_SERVICES = [
+  {
+    id: 'tree-services',
+    name: 'Tree Services',
+    description: 'Professional tree trimming, pruning, and removal services',
+    icon: TreePine,
+    estimatedCost: '5,000 - 20,000',
+    estimatedTime: '1-3 weeks',
+  },
+  {
+    id: 'pool-services',
+    name: 'Pool Services',
+    description: 'Complete pool maintenance, cleaning, and equipment servicing',
+    icon: Waves,
+    estimatedCost: '3,000 - 12,000',
+    estimatedTime: '1-2 weeks',
+  },
+  {
+    id: 'landscape-design',
+    name: 'Landscape Design',
+    description: 'Professional landscaping design and implementation for your property',
+    icon: Leaf,
+    estimatedCost: '10,000 - 50,000',
+    estimatedTime: '2-6 weeks',
+  },
+  {
+    id: 'janitorial-upgrade',
+    name: 'Janitorial Service Enhancement',
+    description: 'Upgrade your cleaning services with specialized equipment and techniques',
+    icon: Paintbrush,
+    estimatedCost: '5,000 - 20,000',
+    estimatedTime: '1-3 weeks',
+  },
+];